Repository toddpla/makersbnb, pull requests merged in 2018-11, with the labels that each got.

#68 Ux styling
  app.rb
  coverage/.resultset.json
  spec/features/authentication_spec.rb
  spec/features/registration_spec.rb
  views/bookings/detail.erb
  views/bookings/index.erb
  views/index.erb
  views/nav.erb
  views/sessions/new.erb
  views/spaces/index.erb
  views/users/new.erb
Labels: enhancement

#74 Sms service class
  Gemfile
  Gemfile.lock
  app.rb
  coverage/.resultset.json
  db/migrate/20181108163343_add_phone_number_column_to_users.rb
  db/schema.rb
  lib/sms_message.rb
  lib/sms_service.rb
  lib/user.rb
  spec/fake_client.rb
  spec/features/authentication_spec.rb
  spec/features/registration_spec.rb
  spec/features/sending_sms_spec.rb
  spec/features/web_helpers.rb
  spec/sms_message_spec.rb
  spec/sms_service_spec.rb
  spec/spec_helper.rb
  spec/user_spec.rb
  views/users/new.erb
Labels: enhancement

#83 Route authentication
  app.rb
  spec/features/unathorised_access_redirect_sign_in_spec.rb
Labels: bug

#86 initial chatbox functionality
  app.rb
  db/migrate/20181109154131_add_bookings_messages.rb
  db/migrate/20181109154228_add_message_booking_relationship.rb
  db/migrate/20181109155615_add_user_id_and_timestamp_to_message.rb
  db/migrate/20181109160548_add_timestamp_to_message_table.rb
  db/schema.rb
  lib/booking.rb
  lib/message.rb
  lib/user.rb
  spec/features/chatbox_spec.rb
  spec/features/web_helpers.rb
  views/bookings/detail.erb
  views/sessions/new.erb
Labels: enhancement

#90 second release
  app.rb
  db/migrate/20181109154131_add_bookings_messages.rb
  db/migrate/20181109154228_add_message_booking_relationship.rb
  db/migrate/20181109155615_add_user_id_and_timestamp_to_message.rb
  db/migrate/20181109160548_add_timestamp_to_message_table.rb
  db/schema.rb
  docs/diagrams/MakersBNB_model.jpg
  docs/diagrams/MakersBNB_model.png
  lib/booking.rb
  lib/message.rb
  lib/sms_service.rb
  lib/user.rb
  spec/features/chatbox_spec.rb
  spec/features/sending_sms_spec.rb
  spec/features/unathorised_access_redirect_sign_in_spec.rb
  spec/features/web_helpers.rb
  views/bookings/detail.erb
  views/sessions/new.erb
Labels: bug, documentation, enhancement
